# This file contains dictionary mappings for data fields storing telemetry data to be mapped to instantiated object attributes.

mapping_athlete = {
    "MinAngle": "min_angle",
    "MaxAngle": "max_angle",
    "ArcLength": "arc_length",
    "CatchSlip": "catch_slip",
    "FinishSlip": "finish_slip",
    "Rower Swivel Power": "rower_swivel_power",
    "GateForceX": "gate_force_x",

    "MaxGateForceX": "max_gate_force_x",
    "AvgGateForceX": "average_gate_force_x",
    "Position_Of_MaxF": "position_of_maxf",
    "Catch Force Gradient": "catch_force_gradient",
    "Finish Force Gradient": "finish_force_gradient",
    "SeatMaxVel": "legs_max_vel",
    
    "GateAngle": "gate_angle",
    "GateAngleVel": "gate_angle_vel",
    "SeatPosn": "seat_posn",
    "SeatPosnVel": "seat_posn_vel",
    "BodyArmsVel": "body_arms_vel",
    "SeatLength": "seat_length",
    "Catch Factor": "catch_factor",
    "Recovery Time 1": "recovery_time_1",
    "Recovery Time 2": "recovery_time_2",
    "Recovery Time 3": "recovery_time_3",
    "Recovery Time 4": "recovery_time_4",
    "Hang Time 1": "hang_time_1",
    "Hang Time 2": "hang_time_2",
    "Catch Slip Time": "catch_slip_time",
    "Drive Time 1": "drive_time_1",
    "Drive Time 2": "drive_time_2",
    "Drive Time 3": "drive_time_3",
    "Drive Time 4": "drive_time_4",
    "Finish Slip Time": "finish_slip_time",
    "Pause Time 1": "pause_time_1",
    "Pause Time 2": "pause_time_2",
    "Recovery Time 5": "recovery_time_5",
    "Stroke Time": "stroke_time",
    "Total Drive Time": "drive_time",
    "Total Recovery Time": "recovery_time",
    "Difference_25": "difference_25",
    "Difference_50": "difference_50",
    "Difference_75": "difference_75",
    "Difference_Hang": "difference_hang",
    "Difference_Min": "difference_min",
    "Difference_Catch": "difference_catch",
    "Difference_Effective_Start": "difference_effective_start",
    "Difference_70Max": "difference_70max",
    "Difference_MaxF": "difference_maxf",
    "Difference_Max70": "difference_max70",
    "Difference_Effective_End": "difference_effective_end",
    "Difference_Finish": "difference_finish",
    "Difference_Max": "difference_max",
    "Difference_Recovery": "difference_recovery",
}

mapping_session = {
    "Rating": "rating",
    "Average Power": "averagepower",
    "Distance / Stroke": "distanceperstroke",
    "Stroke Time": "stroketime",
    "Meters/s": "meterspersecond",
    "Acceleration": "acceleration",
    "Normalized Time": "normalizedtime",
    "GPS": "gps",
}